# Generated by Django 6.0.4 on 2026-04-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=500)),
                ('name_ru', models.CharField(max_length=500)),
                ('description', models.TextField()),
            ],
        ),
    ]
